"""Stable machine-readable application error codes."""

from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_UNAUTHENTICATED = "AUTH_UNAUTHENTICATED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
    AUTH_SCOPE_VIOLATION = "AUTH_SCOPE_VIOLATION"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    ORG_STRUCTURE_NOT_EDITABLE = "ORG_STRUCTURE_NOT_EDITABLE"
    ORG_STRUCTURE_CYCLE = "ORG_STRUCTURE_CYCLE"
    ORG_STRUCTURE_MULTIPLE_ROOTS = "ORG_STRUCTURE_MULTIPLE_ROOTS"
    ORG_STRUCTURE_INVALID_RELATIONSHIP = "ORG_STRUCTURE_INVALID_RELATIONSHIP"
    ORG_STRUCTURE_VERSION_CONFLICT = "ORG_STRUCTURE_VERSION_CONFLICT"
    STAFFING_SLOT_NOT_AVAILABLE = "STAFFING_SLOT_NOT_AVAILABLE"
    STAFFING_FTE_EXCEEDED = "STAFFING_FTE_EXCEEDED"
    EMPLOYEE_ALREADY_ASSIGNED = "EMPLOYEE_ALREADY_ASSIGNED"
    ASSIGNMENT_DATE_CONFLICT = "ASSIGNMENT_DATE_CONFLICT"
    DELEGATION_DATE_CONFLICT = "DELEGATION_DATE_CONFLICT"
    SENSITIVE_DATA_FORBIDDEN = "SENSITIVE_DATA_FORBIDDEN"
