"""Create the complete Module 1 PostgreSQL schema.

Revision ID: 0001_module1_initial
Revises:
Create Date: 2026-07-15
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_module1_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        "ix_audit_events_actor_occurred", "audit_events", ["actor_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_entity",
        "audit_events",
        ["entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_organization_occurred",
        "audit_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("code", name="uq_organizations_code"),
    )
    op.create_index("ix_organizations_status", "organizations", ["status"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_events_attempts_nonnegative")),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_outbox_events_schema_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        "ix_outbox_events_pending",
        "outbox_events",
        ["available_at", "occurred_at"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=160), nullable=False),
        sa.Column("last_name", sa.String(length=160), nullable=False),
        sa.Column("middle_name", sa.String(length=160), nullable=True),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("protected_iin", sa.LargeBinary(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("personal_email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name="uq_permissions_code"),
    )
    op.create_index("ix_permissions_active", "permissions", ["active"], unique=False)
    op.create_table(
        "access_scopes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "organization_id IS NOT NULL",
            name=op.f("ck_access_scopes_ck_access_scopes_organization_required"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_access_scopes_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_scopes")),
    )
    op.create_index(
        "ix_access_scopes_organization",
        "access_scopes",
        ["organization_id", "scope_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_scopes_organization_id"), "access_scopes", ["organization_id"], unique=False
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("employee_number", sa.String(length=64), nullable=False),
        sa.Column("employment_status", sa.String(length=32), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("termination_date", sa.Date(), nullable=True),
        sa.Column("corporate_email", sa.String(length=320), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "termination_date IS NULL OR termination_date >= hire_date",
            name=op.f("ck_employees_ck_employees_valid_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_employees_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_employees_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint(
            "organization_id", "employee_number", name="uq_employees_organization_number"
        ),
        sa.UniqueConstraint(
            "organization_id", "person_id", name="uq_employees_organization_person"
        ),
    )
    op.create_index(
        "ix_employees_organization_active_status",
        "employees",
        ["organization_id", "active", "employment_status"],
        unique=False,
    )
    op.create_table(
        "organization_relationship_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("directed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("prevents_cycles", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("allow_self_link", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "metadata_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f(
                "ck_organization_relationship_types_ck_organization_relationship_types_revision_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_relationship_types_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_relationship_types")),
        sa.UniqueConstraint(
            "organization_id", "code", name="uq_organization_relationship_types_code"
        ),
    )
    op.create_index(
        "ix_organization_relationship_types_active",
        "organization_relationship_types",
        ["organization_id", "active"],
        unique=False,
    )
    op.create_table(
        "organization_unit_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "custom_fields_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f("ck_organization_unit_types_ck_organization_unit_types_revision_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_unit_types_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_unit_types")),
        sa.UniqueConstraint("organization_id", "code", name="uq_organization_unit_types_code"),
    )
    op.create_index(
        "ix_organization_unit_types_active",
        "organization_unit_types",
        ["organization_id", "active"],
        unique=False,
    )
    op.create_table(
        "position_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("job_family", sa.String(length=128), nullable=True),
        sa.Column("grade", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "custom_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f("ck_position_definitions_ck_position_definitions_revision_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_position_definitions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_definitions")),
        sa.UniqueConstraint(
            "organization_id", "code", name="uq_position_definitions_organization_code"
        ),
    )
    op.create_index(
        "ix_position_definitions_active",
        "position_definitions",
        ["organization_id", "active"],
        unique=False,
    )
    op.create_index(
        "ix_position_definitions_job_family",
        "position_definitions",
        ["organization_id", "job_family"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_roles_ck_roles_revision_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index("ix_roles_active", "roles", ["active"], unique=False)
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_index(
        "uq_roles_global_code",
        "roles",
        ["code"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_index(
        "uq_roles_organization_code",
        "roles",
        ["organization_id", "code"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_table(
        "delegations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("delegator_employee_id", sa.Uuid(), nullable=False),
        sa.Column("delegate_employee_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=40), nullable=False),
        sa.Column("scope_reference", sa.String(length=500), nullable=True),
        sa.Column("delegated_permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "delegator_employee_id <> delegate_employee_id",
            name=op.f("ck_delegations_ck_delegations_distinct_employees"),
        ),
        sa.CheckConstraint(
            "effective_to > effective_from", name=op.f("ck_delegations_ck_delegations_valid_dates")
        ),
        sa.ForeignKeyConstraint(
            ["delegate_employee_id"],
            ["employees.id"],
            name=op.f("fk_delegations_delegate_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delegator_employee_id"],
            ["employees.id"],
            name=op.f("fk_delegations_delegator_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delegations")),
    )
    op.create_index(
        "ix_delegations_delegate_effective",
        "delegations",
        ["delegate_employee_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_delegations_delegator_effective",
        "delegations",
        ["delegator_employee_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "organization_unit_type_allowed_parents",
        sa.Column("unit_type_id", sa.UUID(), nullable=False),
        sa.Column("parent_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_type_id"],
            ["organization_unit_types.id"],
            name=op.f(
                "fk_organization_unit_type_allowed_parents_parent_type_id_organization_unit_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_type_id"],
            ["organization_unit_types.id"],
            name=op.f(
                "fk_organization_unit_type_allowed_parents_unit_type_id_organization_unit_types"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "unit_type_id", "parent_type_id", name="pk_organization_unit_type_allowed_parents"
        ),
    )
    op.create_table(
        "user_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_user_accounts_ck_user_accounts_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_user_accounts_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_accounts")),
    )
    op.create_index(
        op.f("ix_user_accounts_employee_id"), "user_accounts", ["employee_id"], unique=False
    )
    op.create_foreign_key(
        "fk_employees_created_by_user_accounts",
        "employees",
        "user_accounts",
        ["created_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        "uq_user_accounts_external_subject_active",
        "user_accounts",
        ["external_subject"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_index(
        "uq_user_accounts_username_active",
        "user_accounts",
        ["username"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "organization_structure_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("based_on_version_id", sa.UUID(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("organization_id"), "="),
            (sa.text("daterange(effective_from, effective_to, '[]')"), "&&"),
            where=sa.text("status = 'published'"),
            using="gist",
            name="excl_organization_structure_versions_published_overlap",
        ),
        sa.CheckConstraint(
            "status <> 'published' OR effective_from IS NOT NULL",
            name=op.f(
                "ck_organization_structure_versions_ck_organization_structure_versions_published_effective_from"
            ),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f(
                "ck_organization_structure_versions_ck_organization_structure_versions_effective_range"
            ),
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f(
                "ck_organization_structure_versions_ck_organization_structure_versions_revision_positive"
            ),
        ),
        sa.CheckConstraint(
            "version_number > 0",
            name=op.f(
                "ck_organization_structure_versions_ck_organization_structure_versions_number_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["based_on_version_id"],
            ["organization_structure_versions.id"],
            name=op.f(
                "fk_organization_structure_versions_based_on_version_id_organization_structure_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_organization_structure_versions_created_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_structure_versions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["user_accounts.id"],
            name=op.f("fk_organization_structure_versions_published_by_user_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_structure_versions")),
        sa.UniqueConstraint(
            "organization_id", "version_number", name="uq_organization_structure_versions_number"
        ),
    )
    op.create_index(
        "ix_organization_structure_versions_active",
        "organization_structure_versions",
        ["organization_id", "status", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_organization_structure_versions_based_on",
        "organization_structure_versions",
        ["based_on_version_id"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["user_accounts.id"],
            name=op.f("fk_role_permissions_granted_by_user_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name="pk_role_permissions"),
    )
    op.create_index(
        "ix_role_permissions_permission_id", "role_permissions", ["permission_id"], unique=False
    )
    op.create_table(
        "user_role_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.UUID(), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_user_role_assignments_ck_user_role_assignments_effective_range"),
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f("ck_user_role_assignments_ck_user_role_assignments_revision_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_user_role_assignments_created_by_user_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["user_accounts.id"],
            name=op.f("fk_user_role_assignments_revoked_by_user_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_user_role_assignments_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["access_scopes.id"],
            name=op.f("fk_user_role_assignments_scope_id_access_scopes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_accounts.id"],
            name=op.f("fk_user_role_assignments_user_id_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role_assignments")),
    )
    op.create_index(
        "ix_user_role_assignments_active",
        "user_role_assignments",
        ["user_id", "role_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_user_role_assignments_user_effective",
        "user_role_assignments",
        ["user_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "organization_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("structure_version_id", sa.UUID(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "managers_can_create_employee_drafts",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "managers_can_assign_existing_employees",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "manager_changes_require_hr_approval",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "managers_can_create_staffing_slots",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "staffing_changes_require_finance_review",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "structure_publish_requires_review",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "allow_multiple_unit_heads",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "allow_cross_unit_relationships",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f("ck_organization_policies_ck_organization_policies_effective_range"),
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f("ck_organization_policies_ck_organization_policies_revision_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_accounts.id"],
            name=op.f("fk_organization_policies_created_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_policies_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["structure_version_id"],
            ["organization_structure_versions.id"],
            name=op.f(
                "fk_organization_policies_structure_version_id_organization_structure_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_policies")),
        sa.UniqueConstraint(
            "structure_version_id", name="uq_organization_policies_structure_version"
        ),
    )
    op.create_index(
        "uq_organization_policies_default",
        "organization_policies",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("structure_version_id IS NULL"),
    )
    op.create_table(
        "organization_structure_review_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("structure_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submission_reason", sa.Text(), nullable=True),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f(
                "ck_organization_structure_review_requests_ck_organization_structure_review_requests_revision_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_structure_review_requests_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["user_accounts.id"],
            name=op.f("fk_organization_structure_review_requests_resolved_by_user_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["structure_version_id"],
            ["organization_structure_versions.id"],
            name=op.f(
                "fk_organization_structure_review_requests_structure_version_id_organization_structure_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["user_accounts.id"],
            name=op.f("fk_organization_structure_review_requests_submitted_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_structure_review_requests")),
    )
    op.create_index(
        "ix_organization_structure_review_requests_status",
        "organization_structure_review_requests",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_organization_structure_review_requests_pending",
        "organization_structure_review_requests",
        ["structure_version_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "organization_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("structure_version_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("unit_type_id", sa.UUID(), nullable=False),
        sa.Column("parent_unit_id", sa.UUID(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "custom_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f("ck_organization_units_ck_organization_units_revision_positive"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f("ck_organization_units_ck_organization_units_sort_order_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_unit_id", "structure_version_id"],
            ["organization_units.id", "organization_units.structure_version_id"],
            name="fk_organization_units_parent_same_version",
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["structure_version_id"],
            ["organization_structure_versions.id"],
            name=op.f("fk_organization_units_structure_version_id_organization_structure_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_type_id"],
            ["organization_unit_types.id"],
            name=op.f("fk_organization_units_unit_type_id_organization_unit_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_units")),
        sa.UniqueConstraint("id", "structure_version_id", name="uq_organization_units_id_version"),
        sa.UniqueConstraint(
            "structure_version_id", "code", name="uq_organization_units_version_code"
        ),
        sa.UniqueConstraint(
            "structure_version_id", "stable_key", name="uq_organization_units_version_stable_key"
        ),
    )
    op.create_index(
        "ix_organization_units_stable_key", "organization_units", ["stable_key"], unique=False
    )
    op.create_index(
        "ix_organization_units_tree",
        "organization_units",
        ["structure_version_id", "parent_unit_id", "active", "sort_order"],
        unique=False,
    )
    op.create_index(
        "uq_organization_units_single_active_root",
        "organization_units",
        ["structure_version_id"],
        unique=True,
        postgresql_where=sa.text("parent_unit_id IS NULL AND active"),
    )
    op.create_table(
        "access_scope_units",
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["access_scopes.id"],
            name=op.f("fk_access_scope_units_scope_id_access_scopes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["organization_units.id"],
            name=op.f("fk_access_scope_units_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("scope_id", "unit_id", name="pk_access_scope_units"),
    )
    op.create_index(
        "ix_access_scope_units_unit_id", "access_scope_units", ["unit_id"], unique=False
    )
    op.create_table(
        "organization_relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("structure_version_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type_id", sa.UUID(), nullable=False),
        sa.Column("source_unit_id", sa.UUID(), nullable=False),
        sa.Column("target_unit_id", sa.UUID(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f(
                "ck_organization_relationships_ck_organization_relationships_effective_range"
            ),
        ),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f(
                "ck_organization_relationships_ck_organization_relationships_revision_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["relationship_type_id"],
            ["organization_relationship_types.id"],
            name=op.f(
                "fk_organization_relationships_relationship_type_id_organization_relationship_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_organization_relationships_source_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["structure_version_id"],
            ["organization_structure_versions.id"],
            name=op.f(
                "fk_organization_relationships_structure_version_id_organization_structure_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_organization_relationships_target_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_relationships")),
    )
    op.create_index(
        "ix_organization_relationships_source_target",
        "organization_relationships",
        ["source_unit_id", "target_unit_id"],
        unique=False,
    )
    op.create_index(
        "ix_organization_relationships_version_active",
        "organization_relationships",
        ["structure_version_id", "active"],
        unique=False,
    )
    op.create_table(
        "staffing_slots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("structure_version_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.UUID(), nullable=False),
        sa.Column("organization_unit_id", sa.UUID(), nullable=False),
        sa.Column("position_definition_id", sa.UUID(), nullable=False),
        sa.Column("reports_to_slot_id", sa.UUID(), nullable=True),
        sa.Column("head_of_unit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "full_time_equivalent",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("1.00"),
            nullable=False,
        ),
        sa.Column("employment_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "custom_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f("ck_staffing_slots_ck_staffing_slots_effective_range"),
        ),
        sa.CheckConstraint(
            "full_time_equivalent > 0 AND full_time_equivalent <= 1",
            name=op.f("ck_staffing_slots_ck_staffing_slots_fte_range"),
        ),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_staffing_slots_ck_staffing_slots_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_staffing_slots_organization_unit_id_organization_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["position_definition_id"],
            ["position_definitions.id"],
            name=op.f("fk_staffing_slots_position_definition_id_position_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reports_to_slot_id"],
            ["staffing_slots.id"],
            name=op.f("fk_staffing_slots_reports_to_slot_id_staffing_slots"),
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["structure_version_id"],
            ["organization_structure_versions.id"],
            name=op.f("fk_staffing_slots_structure_version_id_organization_structure_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staffing_slots")),
        sa.UniqueConstraint(
            "structure_version_id", "stable_key", name="uq_staffing_slots_version_stable_key"
        ),
    )
    op.create_index(
        "ix_staffing_slots_active_head",
        "staffing_slots",
        ["organization_unit_id", "head_of_unit"],
        unique=False,
        postgresql_where=sa.text("status NOT IN ('closing', 'closed')"),
    )
    op.create_index(
        "ix_staffing_slots_reports_to", "staffing_slots", ["reports_to_slot_id"], unique=False
    )
    op.create_index(
        "ix_staffing_slots_version_unit_status",
        "staffing_slots",
        ["structure_version_id", "organization_unit_id", "status"],
        unique=False,
    )
    op.create_table(
        "employee_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("staffing_slot_id", sa.Uuid(), nullable=False),
        sa.Column("assignment_type", sa.String(length=32), nullable=False),
        sa.Column("full_time_equivalent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("primary", sa.Boolean(), nullable=False),
        sa.Column("acting", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("employee_id"), "="),
            (sa.text("daterange(effective_from, effective_to, '[]')"), "&&"),
            where=sa.text(
                '"primary" AND status IN '
                "('pending_review', 'planned', 'active', 'scheduled_end', 'ended')"
            ),
            using="gist",
            name="ex_employee_assignments_one_primary_period",
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_employee_assignments_ck_assignments_valid_dates"),
        ),
        sa.CheckConstraint(
            "full_time_equivalent <= 1",
            name=op.f("ck_employee_assignments_ck_assignments_fte_maximum"),
        ),
        sa.CheckConstraint(
            "full_time_equivalent > 0",
            name=op.f("ck_employee_assignments_ck_assignments_fte_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_assignments_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staffing_slot_id"],
            ["staffing_slots.id"],
            name=op.f("fk_employee_assignments_staffing_slot_id_staffing_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_assignments")),
    )
    op.create_index(
        "ix_assignments_employee_effective",
        "employee_assignments",
        ["employee_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_assignments_slot_effective",
        "employee_assignments",
        ["staffing_slot_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "employee_assignment_review_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submission_reason", sa.Text(), nullable=False),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "revision > 0",
            name=op.f(
                "ck_employee_assignment_review_requests_ck_employee_assignment_reviews_revision_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["employee_assignments.id"],
            name=op.f("fk_employee_assignment_review_requests_assignment_id_employee_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_employee_assignment_review_requests_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["user_accounts.id"],
            name=op.f("fk_employee_assignment_review_requests_resolved_by_user_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["user_accounts.id"],
            name=op.f("fk_employee_assignment_review_requests_submitted_by_user_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_assignment_review_requests")),
    )
    op.create_index(
        "ix_employee_assignment_reviews_organization_status",
        "employee_assignment_review_requests",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_employee_assignment_reviews_pending",
        "employee_assignment_review_requests",
        ["assignment_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION reject_audit_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'audit events are append-only'
                USING ERRCODE = '55000';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_immutable
        BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_events
        FOR EACH STATEMENT
        EXECUTE FUNCTION reject_audit_event_mutation()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation()")
    # btree_gist may be shared by other schemas, so a downgrade intentionally preserves it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_employee_assignment_reviews_pending",
        table_name="employee_assignment_review_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "ix_employee_assignment_reviews_organization_status",
        table_name="employee_assignment_review_requests",
    )
    op.drop_table("employee_assignment_review_requests")
    op.drop_index("ix_assignments_slot_effective", table_name="employee_assignments")
    op.drop_index("ix_assignments_employee_effective", table_name="employee_assignments")
    op.drop_table("employee_assignments")
    op.drop_index("ix_staffing_slots_version_unit_status", table_name="staffing_slots")
    op.drop_index("ix_staffing_slots_reports_to", table_name="staffing_slots")
    op.drop_index(
        "ix_staffing_slots_active_head",
        table_name="staffing_slots",
        postgresql_where=sa.text("status NOT IN ('closing', 'closed')"),
    )
    op.drop_table("staffing_slots")
    op.drop_index(
        "ix_organization_relationships_version_active", table_name="organization_relationships"
    )
    op.drop_index(
        "ix_organization_relationships_source_target", table_name="organization_relationships"
    )
    op.drop_table("organization_relationships")
    op.drop_index("ix_access_scope_units_unit_id", table_name="access_scope_units")
    op.drop_table("access_scope_units")
    op.drop_index(
        "uq_organization_units_single_active_root",
        table_name="organization_units",
        postgresql_where=sa.text("parent_unit_id IS NULL AND active"),
    )
    op.drop_index("ix_organization_units_tree", table_name="organization_units")
    op.drop_index("ix_organization_units_stable_key", table_name="organization_units")
    op.drop_table("organization_units")
    op.drop_index(
        "uq_organization_structure_review_requests_pending",
        table_name="organization_structure_review_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "ix_organization_structure_review_requests_status",
        table_name="organization_structure_review_requests",
    )
    op.drop_table("organization_structure_review_requests")
    op.drop_index(
        "uq_organization_policies_default",
        table_name="organization_policies",
        postgresql_where=sa.text("structure_version_id IS NULL"),
    )
    op.drop_table("organization_policies")
    op.drop_index("ix_user_role_assignments_user_effective", table_name="user_role_assignments")
    op.drop_index(
        "ix_user_role_assignments_active",
        table_name="user_role_assignments",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("user_role_assignments")
    op.drop_index("ix_role_permissions_permission_id", table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(
        "ix_organization_structure_versions_based_on", table_name="organization_structure_versions"
    )
    op.drop_index(
        "ix_organization_structure_versions_active", table_name="organization_structure_versions"
    )
    op.drop_table("organization_structure_versions")
    op.drop_constraint("fk_employees_created_by_user_accounts", "employees", type_="foreignkey")
    op.drop_index(
        "uq_user_accounts_username_active",
        table_name="user_accounts",
        postgresql_where=sa.text("active"),
    )
    op.drop_index(
        "uq_user_accounts_external_subject_active",
        table_name="user_accounts",
        postgresql_where=sa.text("active"),
    )
    op.drop_index(op.f("ix_user_accounts_employee_id"), table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_table("organization_unit_type_allowed_parents")
    op.drop_index("ix_delegations_delegator_effective", table_name="delegations")
    op.drop_index("ix_delegations_delegate_effective", table_name="delegations")
    op.drop_table("delegations")
    op.drop_index(
        "uq_roles_organization_code",
        table_name="roles",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_roles_global_code",
        table_name="roles",
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_index("ix_roles_active", table_name="roles")
    op.drop_table("roles")
    op.drop_index("ix_position_definitions_job_family", table_name="position_definitions")
    op.drop_index("ix_position_definitions_active", table_name="position_definitions")
    op.drop_table("position_definitions")
    op.drop_index("ix_organization_unit_types_active", table_name="organization_unit_types")
    op.drop_table("organization_unit_types")
    op.drop_index(
        "ix_organization_relationship_types_active", table_name="organization_relationship_types"
    )
    op.drop_table("organization_relationship_types")
    op.drop_index("ix_employees_organization_active_status", table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_access_scopes_organization_id"), table_name="access_scopes")
    op.drop_index("ix_access_scopes_organization", table_name="access_scopes")
    op.drop_table("access_scopes")
    op.drop_index("ix_permissions_active", table_name="permissions")
    op.drop_table("permissions")
    op.drop_table("people")
    op.drop_index(
        "ix_outbox_events_pending",
        table_name="outbox_events",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_organizations_status", table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_organization_occurred", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_occurred", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
